### ISSUE TITLE
High FoV issue

### ISSUE THREAD

**Issue by Westlaketea** [Drahsid/BetterShadows#5]
Hi!
I wanted to ask, is it possible to somehow solve the problem with portrait FoV (shadows become pixelated)? 
Example of what I mean: top image with regular FoV, bottom with portrait FoV: 
https://imgur.com/a/xGmpaGt
(maybe these are just just xiv engine things idk)

I would also like to ask if it is possible to add an option to return default presets into plugin, 
and make it possible to display it in gpose.

And maybe add 8k shadows option c:

Thank you!

**Comment by Drahsid** [comment]
> I wanted to ask, is it possible to somehow solve the problem with portrait FoV (shadows become pixelated)?
> Example of what I mean: top image with regular FoV, bottom with portrait FoV:
https://imgur.com/a/xGmpaGt

Your actual perspective (fov, aspect ratio, near and far planes) effect how the shadowmaps appear. This is a consequence of the implementation that the game uses, and I can't fix that.
Another thing to keep in mind is the size of the actual map you are on changes how valuable individual [texels](https://en.wikipedia.org/wiki/Texel_(graphics)) are to the appearance of the shadows. Fortunately, adjusting the cascade distances also affects this, though this is why it is pretty much impossible to make maps like Palace of the Dead look good, since it's massive.
This is related to issue #2 and #3 

> And maybe add 8k shadows option c:
I have tried this and done some reverse engineering on the shadow system. The limitation seems like an issue with either the shadow shader, or dx11 (4k * 4 cascades = 16k, which is the max texture size allowed in dx11). Since the game is coming to Xbox platforms, and with the graphics update looming, I reckon the near future will add support for dx12, which may make this easier.

> I would also like to ask if it is possible to add an option to return default presets into plugin,
See issue #4 , I will add this in a future update

> and make it possible to display it in gpose.
I'm not really a gposer, so I never considered this, but it seems like a good idea. I'll look into this.

**Comment by Drahsid** [comment]
Just a little update, I have added the option to open the shadow configuration window when you begin gposing. You should see it when the latest update goes live on Dalamud. 
Furthermore, as I mentioned in issue #4 , there is now a "Recover Default Presets" button.
Finally, you can now configure the shadow resolution up to 16k. Let me know if the primary issue of this post is resolved by this.
